# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.8.9 on Thu Jun  3 12:44:55 2021
# Model: Habitat Quality

import natcap.invest.habitat_quality
print("InVEST Habitat model : initiated")
args = {
    'half_saturation_constant': '0.075',
    'lulc_cur_path': 'C:/Users/kuelling/Documents/VALPAR/DATA/OFS25_DS/2018/results/LU-CH_2018.tif',
    'results_suffix': '_18',
    'sensitivity_table_path': 'C:/Users/kuelling/Documents/VALPAR/ES Assessment/Habitat_quality/FINAL/SUPPLY/CODE/BPTABLE/hab_sensitivity.csv',
    'threat_raster_folder': 'C:/Users/kuelling/Documents/VALPAR/ES Assessment/Habitat_quality/FINAL/SUPPLY/CODE/BPTABLE/layer_build/LAYERPROD',
    'threats_table_path': 'C:/Users/kuelling/Documents/VALPAR/ES Assessment/Habitat_quality/FINAL/SUPPLY/CODE/BPTABLE/18_threats.csv',
    'workspace_dir': 'C:/Users/kuelling/Documents/VALPAR/ES Assessment/Habitat_quality/FINAL/SUPPLY/CODE/INVEST/18',
}
print("starting...")

if __name__ == '__main__':
    natcap.invest.habitat_quality.execute(args)

print("...done!")
