# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.8.9 on Thu Jun  3 12:44:55 2021
# Model: Habitat Quality

import natcap.invest.habitat_quality

args = {
    'half_saturation_constant': '0.075',
    'lulc_cur_path': 'C:/Users/kuelling/Documents/VALPAR/DATA/Data CRS extent '
                     'ok/geotif_new_extent/LULC_95-97.tif',
    'results_suffix': 'md1',
    'sensitivity_table_path': 'C:/Users/kuelling/Documents/VALPAR/ES '
                              'Assessment/Habitat_quality/data/sensitivity.csv',
    'threat_raster_folder': 'C:/Users/kuelling/Documents/VALPAR/ES '
                            'Assessment/Habitat_quality/data/threat_rasters',
    'threats_table_path': 'C:/Users/kuelling/Documents/VALPAR/ES '
                          'Assessment/Habitat_quality/data/threats.csv',
    'workspace_dir': 'C:\\Users\\kuelling\\Documents\\VALPAR\\ES Assessment\\Habitat_quality\\inVEST\\1\\md2_0075',
}

if __name__ == '__main__':
    natcap.invest.habitat_quality.execute(args)
