# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.8.9 on Wed Oct 20 16:21:06 2021
# Model: Hydropower Water Yield

import natcap.invest.hydropower.hydropower_water_yield

print("InVEST WY model : initiated")
args = {
    'biophysical_table_path': 'C:/Users/kuelling/Documents/VALPAR/ES Assessment/Annual water yield/FINAL/SUPPLY/CODE/BPTABLE/wy_bptable_ds25.csv',
    'depth_to_root_rest_layer_path': 'C:/Users/kuelling/Documents/VALPAR/DATA/Maps.Geo.Soils/Processed_data/Root_restricting_depth/rrd_100_mm_rexport.tif',
    'do_scarcity_and_valuation': False,
    'eto_path': 'C:/Users/kuelling/Documents/VALPAR/DATA/UNIL_data/bioclim25/evapotranspiration/ch_bioclim_chclim25_present_pixel_2000_2009_etp.tif',
    'lulc_path': 'C:/Users/kuelling/Documents/VALPAR/DATA/OFS25_DS/2009/results/LU-CH_2009.tif',
    'pawc_path': 'C:/Users/kuelling/Documents/VALPAR/DATA/Maps.Geo.Soils/Processed_data/Soil_water_storage_capacity/Water_storage_capacity_100m_reclassified1.tif',
    'precipitation_path': 'C:/Users/kuelling/Documents/VALPAR/DATA/UNIL_data/bioclim25/precipitations/ch_bioclim_chclim25_present_pixel_2000_2009_prec.tif',
    'results_suffix': '_09',
    'seasonality_constant': '25',
    'sub_watersheds_path': 'C:/Users/kuelling/Documents/VALPAR/DATA/UNIL_data/catchment_epsg2056/catchment_epsg2056/catchment_epsg2056.shp',
    'watersheds_path': 'C:/Users/kuelling/Documents/VALPAR/DATA/HADES/atlas/Atlas_63_Bassins_LV95.shp',
    'workspace_dir': 'C:/Users/kuelling/Documents/VALPAR/ES Assessment/Annual water yield/FINAL/SUPPLY/CODE/INVEST/09',
}

print("...starting")

if __name__ == '__main__':
    natcap.invest.hydropower.hydropower_water_yield.execute(args)
